version=0.1.4
url=https://github.com/dylandoldersum/rs-realm-launcher/releases/download/v0.1.0/fiddled-client.jar
sha256=9a7331485f94889c31928bab2d2c6b5251f0844a95598e081eb8fdac4c74182e
changelog=Tempoross has been added \n Trading has been fixed
