version=0.1.0
url=https://raw.githubusercontent.com/dylandoldersum/rs-realm-launcher/main/fiddled-client.jar
sha256=
changelog=Eerste beta.\n- Construction\n- Woodcutting/Mining fixes\n- Nieuwe shops
