version=0.1.4
url=https://github.com/dylandoldersum/rs-realm-launcher/releases/download/v0.1.0/fiddled-client.jar
sha256=8ab6ddb77fc32bde89575fcbb1068004aa31248f7fcfae744a9257e54f5f43ab
changelog=-Tempoross has been added \n-Trading has been fixed
